DEBUG = True

MYSQL_DATABASE_USER = 'user'
MYSQL_DATABASE_PASSWORD = 'pass'
MYSQL_DATABASE_DB = 'opptools'
MYSQL_DATABASE_HOST = 'localhost'

MIN_CONFIDENCE = 0.6
MAX_SPAM = 0.4
DOCS_PER_PAGE = 20

SECRET_KEY = 'whatever'

ROOT_DIR = ''
