
SET NAMES 'utf8';

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(128) NOT NULL,
  email VARCHAR(128) NOT NULL,
  pwhash VARCHAR(128) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_login DATETIME DEFAULT NULL
) ENGINE=InnoDB CHARACTER SET utf8;
